### ISSUE TITLE
Feature: Add multiple ingredients and instructions at once

### ISSUE THREAD

**Issue by angelo-v** [NoelDeMartin/umai#15]
Some websites do not provide JSON-LD data of their recipes and one has to copy the text by hand to Umai.

To simplify this it would be a huge improvement if umai supports adding multiple items (ingredients or instructions) at once.

E.g. if you copy a whole list of incredients they are separated by line break in the clipboard. When pasting them into umai, instead of pasting the whole text in one list item, umai should create a list item for each line in the clipboard.

A similar feature can e.g. be found in Trello checklists and I like it a lot there.

**Comment by NoelDeMartin** [comment]
Hey, thanks for the idea.

I like it, but I'm not sure about the UX implications. This is the feature in Trello you're talking about, right? [Importing checklist items](https://support.atlassian.com/trello/docs/adding-checklists-to-cards/#Importing-Checklist-Items). It seems like their approach is to use newlines as separation and they automatically create different items in the list. But I'm not sure how well that would work for Umai.

For ingredients, I think it could work. Newlines would create separate ingredients; and the implication is that you wouldn't be able to have newlines within ingredients (I'm fine with that).

But instructions are more tricky. It's not uncommon to have line breaks within the same instruction step. Maybe I can look for two or more empty lines in a row, or markdown-style list items (like having a `-`, `*`, `+`, or `{number}.` at the beginning). However, even those could give some false positives, so I think I would only do that when creating new steps (and maybe show a notification explaining what happened). But I wouldn't enable this behaviour to edit existing steps.

Maybe to be consistent, this could also happen only for creating new ingredients, not editing.

What do you think?

**Comment by angelo-v** [comment]
Hi Noel, I Understand your concerns, did not think about intentional new lines. Yet I think it is easier to merge to items that have been split by accident than it is to copy over every single item manually.

I am ok witj the idea of supporting this only for new items. Usually if you copy over a whole list there is no item yet. I imagine one won't write one or two items and then copy over a list. It's either manual typing everything or copy-pasting everything

**Comment by NoelDeMartin** [comment]
Ok, I'll keep it in mind for next time I work on the app. Since it's an improvement and not a bug, it'll probably take a while until I do it myself because I'm focused on other things now. If anyone wants to work on this I'm open to PRs. I think it shouldn't be too difficult to achieve, so I'll be adding the "good first issue" label.

**Comment by NoelDeMartin** [comment]
I implemented this in [v0.1.7](https://github.com/NoelDeMartin/umai/blob/main/CHANGELOG.md#v017---2024-12-03), check it out!

The way it works is parsing new lines when pasting into an input. It only works for ingredients though, for the reasons I mentioned previously.
